version: '3.8'

services:

  php:
    container_name: pragmatic_php
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    restart: unless-stopped
    ports:
      - '9000:9000'
