<?php

namespace App\Http\Controllers;

use App\Http\Requests\AuthenticateRequest;
use App\Http\Requests\BetRequest;
use App\Http\Requests\GetBalanceRequest;
use App\Http\Requests\ResultRequest;
use App\Player;
use App\Services\PragmaticErrorCodesService;
use App\Services\PragmaticServiceInterface;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class PragmaticWalletController extends Controller
{
    private $pragmaticServiceInterface;
    public function __construct(PragmaticServiceInterface $pragmaticServiceInterface)
    {
        $this->pragmaticServiceInterface = $pragmaticServiceInterface;
    }

    /**
     * 3.4 When the game is opening Pragmatic Play receives with URL security token generated by Casino Operator. Using this token
     * Pragmatic Play will ask Casino Operator for player authentication and get the player’s balance.
     *
     * @param AuthenticateRequest $request
     * @return JsonResponse
     */
    public function authenticate(AuthenticateRequest $request): JsonResponse
    {
        logger()->channel('pragmatic')->info('Authenticate', $request->all());

        /** @var Player $player */
        $player = $this->pragmaticServiceInterface->getPlayerByToken($request->input('token'));

        if (! $player) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getAuthenticationFailedCode(),
                'description' => 'Invalid or expired or not found token',
            ]);
        }

        if ($player->balance <= 0 && $player->bonus <= 0) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getInsufficientBalanceCode(),
                'description' => 'Insufficient balance',
            ]);
        }

        if ($player->is_banned) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getPlayerFrozenCode(),
                'description' => 'Player is frozen',
            ]);
        }

        return $this->successResponse([
            'userId' => $player->user_id,
            'currency' => $player->currency,
            'cash' => $player->balance,
            'bonus' => $player->bonus
        ]);
    }

    /**
     * 3.5 Balance
     * Using this method a Pragmatic Play system will know a current balance of player and will show it in the game.
     *
     * @param GetBalanceRequest $request
     * @return JsonResponse
     */
    public function balance(GetBalanceRequest $request): JsonResponse
    {
        logger()->channel('pragmatic')->info('Balance', $request->all());

        /** @var Player $player */
        $player = $this->pragmaticServiceInterface->getPlayerByUserId($request->input('userId'));

        if (! $player) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getPlayerNotFoundCode(),
                'description' => 'Player not found',
            ]);
        }

        return $this->successResponse([
            'currency' => $player->currency,
            'cash' => $player->balance,
            'bonus' => $player->bonus,
        ]);
    }

    /**
     * 3.6 Bet
     * Using this method Pragmatic Play system will check the player balance on Casino Operator side to ensure they still have the
     * funds to cover the bet. Amount of the bet must be subtracted from player balance in Casino Operator system.
     *
     * @param BetRequest $request
     * @return JsonResponse
     */
    public function bet(BetRequest $request): JsonResponse
    {
        logger()->channel('pragmatic')->info('Bet', $request->all());

        /** @var Player $player */
        $player = $this->pragmaticServiceInterface->getPlayerByUserId($request->input('userId'));

        if (! $player) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getPlayerNotFoundCode(),
                'description' => 'Player not found',
            ]);
        }

        $transaction = $this->pragmaticServiceInterface->processedBet($player, $request->all());

        if (! $transaction) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getInternalServerErrorRetryCode(),
                'description' => 'Server error',
            ]);
        }

        return $this->successResponse([
            'transactionId' => $transaction->id,
            'currency' => $player->currency,
            'cash' => $player->balance,
            'bonus' => $player->bonus,
            'usedPromo' => 0.00
        ]);
    }

    /**
     * 3.7 Result
     * Using this method the Pragmatic Play system will send to Casino Operator the winning result of a bet.
     * The Casino Operator will change the balance of the player
     * in accordance with this request and return the updated balance.
     *
     * @param ResultRequest $request
     * @return JsonResponse
     */
    public function result(ResultRequest $request): JsonResponse
    {
        logger()->channel('pragmatic')->info('Result', $request->all());

        /** @var Player $player */
        $player = $this->pragmaticServiceInterface->getPlayerByUserId($request->input('userId'));

        if (! $player) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getPlayerNotFoundCode(),
                'description' => 'Player not found',
            ]);
        }

        $transaction = $this->pragmaticServiceInterface->processedWinBet($player, $request->all());

        if (! $transaction) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getInternalServerErrorRetryCode(),
                'description' => 'Server error',
            ]);
        }

        return $this->successResponse([
            'transactionId' => $transaction->id,
            'currency' => $player->currency,
            'cash' => $player->balance,
            'bonus' => $player->bonus,
        ]);
    }

    public function bonusWin(Request $request): JsonResponse
    {
        logger()->channel('pragmatic')->info('Bonus Win', $request->all());

        /** @var Player $player */
        $player = $this->pragmaticServiceInterface->getPlayerByUserId($request->input('userId'));

        if (! $player) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getPlayerNotFoundCode(),
                'description' => 'Player not found',
            ]);
        }

        $transaction = $this->pragmaticServiceInterface->processedBonusWin($player, $request->all());

        if (! $transaction) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getInternalServerErrorRetryCode(),
                'description' => 'Server error',
            ]);
        }

        return $this->successResponse([
            'transactionId' => $transaction->id,
            'currency' => $player->currency,
            'cash' => $player->balance,
            'bonus' => $player->bonus,
        ]);
    }

    public function jackpotWin(Request $request): JsonResponse
    {
        logger()->channel('pragmatic')->info('Jackpot Win', $request->all());

        /** @var Player $player */
        $player = $this->pragmaticServiceInterface->getPlayerByUserId($request->input('userId'));

        if (! $player) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getPlayerNotFoundCode(),
                'description' => 'Player not found',
            ]);
        }

        $transaction = $this->pragmaticServiceInterface->processedJackpotWin($player, $request->all());

        if (! $transaction) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getInternalServerErrorRetryCode(),
                'description' => 'Server error',
            ]);
        }

        return $this->successResponse([
            'transactionId' => $transaction->id,
            'currency' => $player->currency,
            'cash' => $player->balance,
            'bonus' => $player->bonus,
        ]);
    }

    public function endRound(Request $request): JsonResponse
    {
        logger()->channel('pragmatic')->info('End Round', $request->all());

        /** @var Player $player */
        $player = $this->pragmaticServiceInterface->getPlayerByUserId($request->input('userId'));

        if (! $player) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getPlayerNotFoundCode(),
                'description' => 'Player not found',
            ]);
        }

        $this->pragmaticServiceInterface->endRound($player, $request->all());

        return $this->successResponse([
            'cash' => $player->balance,
            'bonus' => $player->bonus,
        ]);
    }

    public function refund(Request $request): JsonResponse
    {
        logger()->channel('pragmatic')->info('Refund', $request->all());

        /** @var Player $player */
        $player = $this->pragmaticServiceInterface->getPlayerByUserId($request->input('userId'));

        if (! $player) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getPlayerNotFoundCode(),
                'description' => 'Player not found',
            ]);
        }

        $transaction = $this->pragmaticServiceInterface->refund($player, $request->all());

        if (! $transaction) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getInternalServerErrorRetryCode(),
                'description' => 'Server error',
            ]);
        }

        return $this->successResponse([
            'transactionId' => $transaction->id,
        ]);
    }

    public function promoWin(Request $request): JsonResponse
    {
        logger()->channel('pragmatic')->info('Promo win', $request->all());

        /** @var Player $player */
        $player = $this->pragmaticServiceInterface->getPlayerByUserId($request->input('userId'));

        if (! $player) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getPlayerNotFoundCode(),
                'description' => 'Player not found',
            ]);
        }

        $transaction = $this->pragmaticServiceInterface->promoWin($player, $request->all());

        if (! $transaction) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getInternalServerErrorRetryCode(),
                'description' => 'Server error',
            ]);
        }

        return $this->successResponse([
            'transactionId' => $transaction->id,
            'currency' => $player->currency,
            'cash' => $player->balance,
            'bonus' => $player->bonus,
        ]);
    }

    public function sessionExpired(Request $request): JsonResponse
    {
        logger()->channel('pragmatic')->info('Session Expired', $request->all());

        /** @var Player $player */
        $player = $this->pragmaticServiceInterface->getPlayerByUserId($request->input('userId'));

        if (! $player) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getPlayerNotFoundCode(),
                'description' => 'Player not found',
            ]);
        }

        $this->pragmaticServiceInterface->sessionExpired($player, $request->all());

        return $this->successResponse();
    }

    public function adjustment(Request $request): JsonResponse
    {
        logger()->channel('pragmatic')->info('Adjustment', $request->all());

        /** @var Player $player */
        $player = $this->pragmaticServiceInterface->getPlayerByUserId($request->input('userId'));

        if (! $player) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getPlayerNotFoundCode(),
                'description' => 'Player not found',
            ]);
        }

        $result = $this->pragmaticServiceInterface->adjustment($player, $request->all());

        if (isset($result['negative_balance'])) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getInsufficientBalanceCode(),
                'description' => 'Insufficient balance',
            ]);
        }

        if (! isset($result['transaction'])) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getInternalServerErrorRetryCode(),
                'description' => 'Server error',
            ]);
        }

        $transaction = $result['transaction'];

        return $this->successResponse([
            'transactionId' => $transaction->id,
            'currency' => $player->currency,
            'cash' => $player->balance,
            'bonus' => $player->bonus,
        ]);
    }

    public function roundDetails(Request $request): JsonResponse
    {
        logger()->channel('pragmatic')->info('Round details', $request->all());

        /** @var Player $player */
        $player = $this->pragmaticServiceInterface->getPlayerByUserId($request->input('userId'));

        if (! $player) {
            return response()->json([
                'error' => PragmaticErrorCodesService::getPlayerNotFoundCode(),
                'description' => 'Player not found',
            ]);
        }

        $this->pragmaticServiceInterface->roundDetails($player, $request->all());

        return $this->successResponse();
    }

    private function successResponse(array $data = []): JsonResponse
    {
        return response()->json(array_merge([
            'error' => PragmaticErrorCodesService::getSuccessCode(),
            'description' => 'OK'
        ], $data));
    }
}
